all:
	g++ -O3 -march=native -ffast-math -I/opt/homebrew/include/eigen3 main/*.cpp camera/*.cpp transformations/*.cpp textures/*.cpp lights/*.cpp parser/*.cpp shapes/*.cpp write/*.cpp -o raytracer -std=c++1z
